# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

networks:
  backend: 

services:
  maiwebsitebackend:
    container_name: maiwebsitebackend_container
    image: maiwebsitebackend
    build: .
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  maiwebsitedb:
    container_name: db_container
    image: mysql:8.0
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: maiwebsite
      MYSQL_PASSWORD: maiwebsite